export { addCatsToAscii } from './ascii/cats.js';
export { statsSection } from './sections/stats.js';
export { languagesSection } from './sections/languages.js';
export { activitySection } from './sections/activity.js';
export { generateReadmeContent, renderReadmeFromData } from './generator.js';
export { renderAscii, processTextForFont, asciiSection } from './sections/asci.js';
export * from './sections/types.js';
export * from './config.js';
export * from './fetcher.js';
export { customFontNames } from './ascii/custom-fonts.js';